### ISSUE TITLE
Cant' build yoshimi on (X)Ubuntu 14.04 anymore

### ISSUE THREAD

**Issue by suedwestlicht** [Yoshimi/yoshimi#47]
- I can build recent yoshimi git head on 16.04
- I can build yoshimi from 2019-01-10 an 14.04, too

But I cant build recent yoshimi git head on 14.04:
```
[  0%] Linking CXX executable yoshimi
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libfltk.a(Fl_x.o): undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libdl.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [yoshimi] Error 1
make[1]: *** [CMakeFiles/yoshimi.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by dbtx** [comment]
Odd, we used to simply add 'dl' into the libraries but now there's a more appropriate check, and apparently that's coming back empty. If you run `cmake -DCMAKE_EXE_LINKER_FLAGS="-ldl" path/to/src` and make again, it will probably work-- at least until we can find out what changed.

**Comment by suedwestlicht** [comment]
No luck:
```
[ 51%] Linking CXX executable yoshimi
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libfltk.a(Fl_x.o): undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libdl.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [yoshimi] Fehler 1
make[1]: *** [CMakeFiles/yoshimi.dir/all] Fehler 2
make: *** [all] Fehler 2
```

**Comment by suedwestlicht** [comment]
It seems to affect the standalone version only. make -j4 builds yoshimi_lv2.so
```
[ 98%] Building CXX object LV2_Plugin/CMakeFiles/yoshimi_lv2.dir/__/UI/WidgetPDial.cpp.o
[ 99%] Building CXX object LV2_Plugin/CMakeFiles/yoshimi_lv2.dir/__/UI/WidgetMWSlider.cpp.o
[100%] Linking CXX shared module yoshimi_lv2.so
[100%] Built target yoshimi_lv2
```

**Comment by dbtx** [comment]
Could you go again, this time adding `-DCMAKE_VERBOSE_MAKEFILE=1` and pasting everything?

**Comment by suedwestlicht** [comment]
Most recent version that builds on 14.04 is:
```
commit 20e9accd3450f6fb50b215640ca12eeff10d7391
Author: abrolag <willgodfrey@musically.me.uk>
Date:   Sun Jan 27 20:32:37 2019 +0000

    Enabled full CLI start sequence .state .xmz .xiz .xly
```

So the problem was introduced with:
```
commit 5a6e271c5e1f5114cfdf1f1a53c3300a9decbbfe
Author: abrolag <willgodfrey@musically.me.uk>
Date:   Fri Feb 1 16:05:05 2019 +0000

    Enabled headless build (Not LV2)

```

**Comment by suedwestlicht** [comment]
```
hm@regen:~/src/yoshimi/2019-02-09a/src$ cmake -DCMAKE_EXE_LINKER_FLAGS="-ldl" -DCMAKE_VERBOSE_MAKEFILE=1 .
-- Building Yoshimi version 1.5.10 M for Linux
-- Found pkg-config /usr/bin/pkg-config
-- Found libz
-- Found fftw3f 3.3.3
-- Found mxml 2.7
-- Found Alsa 1.0.27.2
-- Found jack 1.9.12
-- Found fontconfig 2.11.0
-- Found libcairo 1.13.1
-- Found FLTK
-- Found libncurses or libncursesw
-- Readline library found
-- RELEASE Build, flags: -march=native -Wall -msse -msse2 -mfpmath=sse -ffast-math -fno-finite-math-only -fomit-frame-pointer  -O3
-- With jack session support
-- Found lv2 package 1.14.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hm/src/yoshimi/2019-02-09a/src
```

Log is attached.

[log.txt](https://github.com/Yoshimi/yoshimi/files/2847808/log.txt)

**Comment by dbtx** [comment]
Thank you for that info. Could you try once more, after `git pull origin bugfix` in the source directory? 
(Reasoning) Well, OK, that's a bit bizarre. `-ldl` was already in the command, and manually specifying it seems to have just put it first in line, but ...light bulb. Now I get it. We _did_ change that, the thing that changed was the _order_, the FLTK libraries are getting added to the linker libraries at the end. Before FLTK was made optional, its own libraries appeared nearer to the beginning of the link command line-- and before `-ldl`. The linker needs those libraries meeting requirements to be listed always _after_ the one requiring them. And for some reason, FLTK's pkg-config files (or the cmake module, or whatever) required system libraries don't mention -ldl, at least not in that version of Xubuntu-- which is odd, else it would be near the end along with -lX11, -lGL, -lpng, and so on. Maybe that's why we had it explicitly added at the end of the list some time ago? I don't know, I guess it doesn't matter...

**Comment by suedwestlicht** [comment]
Success! It builds again. Thx.

**Comment by dbtx** [comment]
You're welcome! Thanks for the help and for bringing it up.
